version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: wallet_dev
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - wallet-network

  redis:
    image: redis:7-alpine
    container_name: wallet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - wallet-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://wallet_user:wallet_pass@postgres:5432/wallet_dev
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: info
    networks:
      - wallet-network

volumes:
  postgres_data:
  redis_data:

networks:
  wallet-network:
    driver: bridge

